#!/usr/bin/env ruby

require "copy_pasta"
require "optparse"

options     = { threads: 100 }
permissions = {}

op = OptionParser.new do |opts|
  opts.banner = "Usage: #{$PROGRAM_NAME} [options]"

  opts.on("-sDIRECTORY", "--source-directory=DIRECTORY", "The source directory to copy from") do |t|
    options[:source_directory] = t
  end

  opts.on("-dDIR", "--destination-dir=DIR", "Directory to copy files to") do |dir|
    options[:destination_directory] = dir
  end

  opts.on("-nTHREADS", "--num-threads=THREADS", Integer, "Number of threads to use for extraction (Default: 100)") do |n|
    options[:threads] = n
  end

  opts.on("-pPATTERN", "--pattern=PATTERN", "Extract files that match the ruby Regexp PATTERN") do |t|
    options[:pattern] = t
  end

  opts.on("-uUSER", "--user=USER", "The unix username for chowning each file and directory") do |t|
    permissions[:user] = t
  end

  opts.on("-gGROUP", "--group=GROUP", "The unix group for chowning each file and directory") do |t|
    permissions[:group] = t
  end

  opts.on("--dir-mode=DIRECTORY-MODE", Integer, "The unix mode for each extracted directory") do |t|
    permissions[:directory_mode] = t
  end

  opts.on("--file-mode=FILE-MODE", Integer, "The unix mode for each extracted file") do |t|
    permissions[:file_mode] = t
  end
end

op.parse!

abort op.banner if options[:source_directory].nil? || options[:destination_directory].nil?

input   = CopyPasta::DirectoryReader.new(options.fetch(:source_directory), options[:pattern])
dir     = options.fetch(:destination_directory)
threads = options.fetch(:threads)

created_dirs  = CopyPasta::DirectoryCreator.run(input.directories, dir, threads: threads)
created_files = CopyPasta::FileCreator.run(input.files, dir, threads: threads)

unless permissions.empty?
  permissions[:threads] = threads
  permissions[:mode] = permissions.delete(:directory_mode)
  CopyPasta::Permission.set(created_dirs, permissions)

  permissions[:mode] = permissions.delete(:file_mode)
  CopyPasta::Permission.set(created_files, permissions)
end
