#!/usr/bin/env ruby

require "unthread"

tar_file   = ARGV[0]
output_dir = ARGV[1]

if tar_file.nil? || output_dir.nil?
  abort "Usage: #{$0} <file.tar> <output_dir>"
end

input = Unthread::Entry.new(tar_file)

Unthread::DirectoryCreator.run(input.directories, output_dir, threads: 100)
Unthread::FileCreator.run(input.files, output_dir, threads: 100)
