#!/usr/bin/env ruby

require "unthread"
require "optparse"

options = { threads: 100 }

op = OptionParser.new do |opts|
  opts.banner = "Usage: #{$PROGRAM_NAME} [options] <tar_file>"

  opts.on("-oDIR", "--output-dir=DIR", "Directory to extract files") do |dir|
    options[:output_dir] = dir
  end

  banner = "Number of threads to use for extraction (Default: 100)"

  opts.on("-nTHREADS", "--num-threads=THREADS", Integer, banner) do |n|
    options[:threads] = n
  end

  opts.on("-tTARFILE", "--tar-file=TARFILE", "The tar file to extract") do |t|
    options[:tar_file] = t
  end
end

op.parse!

abort op.banner if options[:tar_file].nil? || options[:output_dir].nil?

input   = Unthread::Entry.new(options.fetch(:tar_file))
dir     = options.fetch(:output_dir)
threads = options.fetch(:threads)

Unthread::DirectoryCreator.run(input.directories, dir, threads: threads)
Unthread::FileCreator.run(input.files, dir, threads: threads)
